name: Package WhyDiscordWhy
run-name: ${{ github.actor }} said "${{ github.event.head_commit.message }}"
on: [push]
jobs:
  windows-release:
    runs-on: windows-latest
    steps:
      - name: Build executable
        uses: actions/checkout@v4
      - run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller --noconfirm --onedir --windowed --add-data "--add-data "C:/Users/%username%/Local/Programs/Python/Python39/Lib/site-packages/customtkinter;customtkinter/" --add-data "ffmpeg;ffmpeg/"  whydiscordwhy.py
      #- name: Zip package
      #  run: |
      #    Compress-Archive -Path dist/whydiscordwhy/* -Destination whydiscordwhy-windows.zip
      #    ls
      - name: Publish package
        uses: actions/upload-artifact@v4
        with:
          name: whydiscordwhy-windows-${{ github.sha }}
          path: dist/whydiscordwhy


